#!/bin/bash
sudo nano /etc/hostname
sudo nano /etc/ssh/sshd_config
sudo nano /etc/netplan/*
sudo apt update
sudo apt upgrade --yes
cd /etc
sudo git clone https://github.com/arne-fuchs/pyUsageApi.git
cd
crontab -l > mycron
echo "@reboot python3 /etc/pyUsageApi/api.py" >> mycron
crontab mycron
rm mycron
sudo apt install python3-pip --yes
pip3 install Flask
pip3 install psutil
pip3 install uptime
sudo apt install net-tools
sudo reboot
