#!/bin/bash
sudo nano /etc/ssh/sshd_config
sudo nano /etc/netplan/00-installer-config.yaml
sudo apt update
sudo apt upgrade
cd /etc
sudo git clone https://github.com/arne-fuchs/pyUsageApi.git
cd
crontab -l > mycron
echo "@reboot python3 /etc/pyUsageApi/api.py" >> mycron
crontab mycron
rm mycron
sudo reboot
