#!/bin/bash
sudo apt update
sudo nano /etc/ssh/sshd.config
sudo nano /etc/netplan/50-cloud-init.yaml
sudo apt upgrade
cd /etc
sudo git clone https://github.com/arne-fuchs/pyUsageApi.git
cd pyUsageApi
sudo ./start
sudo reboot
